name: snapcraft-stack-example
base: core18
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
version-script: "grep version package.yaml | awk '{ print $NF }'"
summary: Snapcraft Haskell Stack example # 79 char long summary
description: Snapcraft Haskell Stack example to test building Haskell projects with Snapcraft

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  app:
    # See 'snapcraft plugins'
    plugin: nil
    source: .
    build-environment:
      - PATH: "/root/.local/bin:$PATH"
    override-build: |
      curl -sSL https://get.haskellstack.org/ | sh 
      which stack
      stack --version
      stack build
    stage-packages:
      - curl
